### ISSUE TITLE
Port 6969 is already in use

### ISSUE THREAD

**Issue by aaronhepner** [apfaffman/fika-3.9.8#1]
After going into the http.json config to set up the ip information as described in the official SPT server documentation, the unraid logs give the error:

Port 6969 is already in use, DO NOT RUN TWO SPT SERVERS. This will result in your progress not saving. Try restarting your computer. [listen EADDRNOTAVAIL: address not available xxx.xxx.xx.xx:6969]
Error: listen EADDRNOTAVAIL: address not available xxx.xxx.xx.xx:6969
Error: listen EADDRNOTAVAIL: address not available xxx.xxx.xx.xx:6969
    at Server.setupListenHandle [as _listen2] (node:net:1855:21)
    at listenInCluster (node:net:1920:12)
    at doListen (node:net:2075:7)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
Error: listen EADDRNOTAVAIL: address not available xxx.xxx.xx.xx:6969
Error: listen EADDRNOTAVAIL: address not available xxx.xxx.xx.xx:6969
    at Server.setupListenHandle [as _listen2] (node:net:1855:21)
    at listenInCluster (node:net:1920:12)
    at doListen (node:net:2075:7)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)

**Comment by apfaffman** [comment]
looks like you sorted this out?

**Comment by aaronhepner** [comment]
I did! I apologize for leaving an issue but I was pulling teeth trying to figure it out. It's interesting that you have to leave the ip info as 0.0.0.0 in order for it to work. Thank you for putting this together!!

**Comment by apfaffman** [comment]
i suspect this has to do with binding the SPT service to the correct interface. by default, the container will be connected to the default docker bridge, which likely doesn't share the same subnet/ip as your physical host. use 0.0.0.0/0 to tell the container to listen to port 6969 on all interfaces, including whatever ip it gets by being on that bridge network.
